### ISSUE TITLE
Add plugin(s) for converting between FuMa and ACN/SN3D B-format

### ISSUE THREAD

**Issue by lossius** [ambisonictoolkit/atk-reaper#10]
As discussed with the Google VR team.

**Comment by DrWig** [comment]
Do you just want to include the JS I made for this?

**Comment by lossius** [comment]
@DrWig : Yes, that would be great. Should I just add the file myself, or do you want to make a Pull request?

**Comment by DrWig** [comment]
i'll do a pull request.  Will add a license to it first.

cheers

Bruce

**Comment by joslloand** [comment]
Hi Trond,

I can generate the matrices. The Python code already does the job.

Hi Trond,

I can do this, actually, and had it in my notes as 'low hanging fruit'.

I was going to take the A-to-B convert and then drop in the new matrices. If you like, I could just forward these to you, and you can drop them in.

Do you have a preference?

**Comment by DrWig** [comment]
No worries if you've already got it sorted. I'm happy to help out if you
ever want it, though......I'm becoming a fan of JS 😉

Cheers

Bruce

**Comment by joslloand** [comment]
@DrWig Thanks for your offer of help here. Its one of those things I've had on a todo list since Trond and I spoke to the GoogleVR team.

This does relate to some possible re-architecting of the way the ATK works with matrices that I've been thinking about. I've updated that in my earlier comment.

One thing I'd like to do is to move all the matrix and kernel generating code to Julia... and publish in the [ATK github repo](https://github.com/ambisonictoolkit).

**Comment by lossius** [comment]
@joslloand has provided me with the necessary matrices. Now it's just a matter of work (and not that much work, really).

**Comment by joslloand** [comment]
@lossius, I'm now thinking that for Reaper workflow this plug-in should be described as an "Ambisonic exchange" plug-in.

In [atk-sc3](https://github.com/ambisonictoolkit/atk-sc3) the functionality will be described as en/decoding.

As we move towards integrating [matrix loading](https://github.com/ambisonictoolkit/atk-matrices), this kind of thing (adding new en/decoding) should be much easier.
